window:
  opacity: 1

font:
  normal:
    family: Monaspace Krypton
    style: Regular
  bold:
    family: Monaspace Krypton
    style: Bold
  italic:
    family: Monaspace Krypton
    style: Italic
  bold_italic:
    family: Monaspace Krypton
    style: Bold Italic
  size: 10
  # size: 7

import:
  - ~/.config/alacritty/tokyonight_storm.yml

mouse:
  hide_when_typing: true

window:
  opacity: 1
  padding:
    x: 1
    y: 1

selection:
  save_to_clipboard: true
