window:
  opacity: 1

font:
  normal:
    family: MonaspiceKr NF 
    style: Regular
  size: 10

import:
  - ~/.config/alacritty/tokyonight_storm.yml

mouse:
  hide_when_typing: true

window:
  opacity: 1
  padding:
    x: 1
    y: 1

selection:
  save_to_clipboard: true
