import = ["/home/qlpth/.config/alacritty/tokyonight_storm.toml"]

[font]
size = 10

[font.normal]
family = "MonaspiceKr NF"
style = "Regular"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
opacity = 1

[window.padding]
x = 1
y = 1
