#! /bin/sh

setxkbmap fr
xinput set-prop "ELAN0521:01 04F3:31B1 Touchpad" "libinput Tapping Enabled" 1

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width	0
bspc config window_gap		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Check with xprop
bspc rule -a obsidian desktop='^4'
bspc rule -a Code desktop='^5'
bspc rule -a Brave-browser desktop='^7'
bspc rule -a discord desktop='^10'


bspc config focused_border_color \#777777
bspc config normal_border_color \#777777


picom &
eww daemon &

bspc config top_padding 33
sh ~/.config/eww/launch_eww.sh &
sh ~/.config/eww/scripts/notifications.sh get &

feh  ~/.config/wallpapers --bg-center --bg-fill --randomize
