[[columns]]
kind = "Pid"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Separator"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "UsageCpu"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "UsageMem"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "MultiSlot"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "Separator"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Command"
numeric_search = false
nonnumeric_search = true
align = "Left"
max_width = 40

[display]
show_header = false
cut_to_pipe = true
cut_to_terminal = true
cut_to_pager = true

[sort]
column = 2
order = "Descending"

[pager]
mode = "Disable"
