# Not good enough, to redo everything


format = '''$username$hostname$directory$git_branch$character '''

add_newline = false


[directory]
read_only = ' 󰌾'
format = '[$path](bold blue)[$read_only](bold yellow) '
truncation_length = 0

[git_branch]
symbol = ''
format = '[$symbol](green) '

[username]
show_always = true
format = '[$user](bold yellow) '

[hostname]
ssh_only = true
format = 'on [$hostname](bold blue) '

[character]
format = '[\$](cyan)'



# Unused
[env_var]
variable = 'TMUX_ENV'
default = ''
format = '[$env_value](bold red)'
