# Not good enough, to redo everything


format = '''$env_var$git_branch$directory$sudo$character '''
add_newline = false


[directory]
read_only = ' 󰌾'
format = '[$path](bold blue)[$read_only](bold yellow) '
truncation_length = 0

[git_branch]
symbol = ''
format = '[git:\(](red)[$branch](#b4befe)[\)](red) '

[character]
format = '[\$](cyan)'

[sudo]
disabled = false
symbol = '!'
format = '[$symbol](red)'

[env_var]
variable = 'TMUX_ENV'
default = 'qlpth'
format = '[$env_value](yellow) '
