#format = '''$username$nix_shell $git_branch$directory$sudo$character '''
format = '''$username$nix_shell $git_branch$directory$sudo$character '''
add_newline = false


[username]
show_always = true
format = '[$user](yellow)'

[directory]
read_only = ' 󰌾'
format = '[$path](bold blue)[$read_only](bold yellow) '
truncation_length = 0

[git_branch]
symbol = ''
format = '[$symbol:\(](red)[$branch](#b4befe)[\)](red)'

[character]
error_symbol = '[\$](red)'
success_symbol = '[\$](green)'
format = '$symbol'

[sudo]
disabled = false
symbol = '!'
format = '[$symbol](red)'

[nix_shell]
disabled = false
format = '\[[$name](green)\]'
