#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh /home/qlpth/.config/wallpapers/3.jpg --be-center --bg-fill &

bspc monitor eDP-1-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sh ~/.config/eww/launch_eww.sh &
alacritty &
