lastupdatecheck: 0
recentrepos:
- /home/qlpth/dev/repo/dotfiles
- /home/qlpth/dev/repo/vault
- /home/qlpth/dev/repo/sandbox
startuppopupversion: 5
customcommandshistory:
- git stash apply
- git config pull.rebase false
- qa
hidecommandlog: false
ignorewhitespaceindiffview: false
